name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
#     - uses: actions/checkout@v2
    - uses: fwal/setup-swift@master
    - name: Check Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
