name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Version
      id: version
      run: swift --version
    - name: Build
      run: swift build -v
      if: contains(steps.version.outputs, "5.2")
    - name: Run tests
      run: swift test -v
      if: contains(steps.version.contains, "5.2")
